package jp.co.codable.mybatissample;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.ID
     *
     * @mbg.generated Thu Feb 15 17:34:15 JST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.NAME
     *
     * @mbg.generated Thu Feb 15 17:34:15 JST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.ID
     *
     * @return the value of PUBLIC.USER.ID
     *
     * @mbg.generated Thu Feb 15 17:34:15 JST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.ID
     *
     * @param id the value for PUBLIC.USER.ID
     *
     * @mbg.generated Thu Feb 15 17:34:15 JST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.NAME
     *
     * @return the value of PUBLIC.USER.NAME
     *
     * @mbg.generated Thu Feb 15 17:34:15 JST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.NAME
     *
     * @param name the value for PUBLIC.USER.NAME
     *
     * @mbg.generated Thu Feb 15 17:34:15 JST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}